Repository Team6090/InfiniteRecharge, pull requests merged in 2020-02, with the labels that each got.

#2 Updated Gradle Version
  gradle/wrapper/gradle-wrapper.properties
Labels: documentation, enhancement, good first issue

#18 Update to SwerveIO 2.1.0
  src/main/java/frc/robot/commands/AutonBallGetter.java
  src/main/java/frc/robot/commands/DriveWithJoystick.java
  src/main/java/frc/robot/subsystems/DriveTrain.java
  vendordeps/Team6090.json
Labels: duplicate, enhancement

#20 Fix warnings in RobotContainer & Fix local dependencies
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  localdeps.gradle
  src/main/java/frc/robot/RobotContainer.java
Labels: enhancement
